final List<String> evaluationCriteria = [
  "Technical merits (%15)",
  "Project design and implementation (realization ratio with respect to its definition) (%40)",
  "Report (completeness and content) (%15)",
  "Presentation (%10)",
  "Demo (%10)",
  "Papers (%10)"
];

final List<String> projectChecklist = [
  "The project contains all the parts that Computer Engineering Department requires (usually Abstract, Acknowledgments, Table of Contents, Introduction, Related Works, etc. Conclusion, References, any Appendices). Some variation is possible. You may not need a separate chapter for Materials and Methods, for example, and not all projects need Appendices.",
  "The Abstract (written last) defines the problem you worked on, clearly states its importance and the method(s) you used to solve it, puts your work into the context of previous work in your field, clearly identifies your findings and their importance, and suggests possible applications. Your unique contribution is clearly delineated. The Abstract literally abstracts the important points in your thesis. It does not merely state what the thesis is about; instead, it summarizes the contents. Finally, your abstract must not exceed the word limit (150 words minimum).",
  "You can write the Acknowledgments any time, but most people write them after the bulk of the thesis has been completed so that you know who has been helpful. Gratitude and diplomacy both demand that you start by thanking your thesis committee, naming your advisor first. Then move either to other faculty who were helpful or to the team members or students you worked with before embarking on this solo thesis project. Then thank friends, if you wish, and end by expressing your most heartfelt gratitude to your family, especially to a long-suffering spouse or partner. This section is the only one in which you express much emotion, and it is acceptable here, but don’t overdo it.",
  "The page numbers in the Table of Contents and List of Tables or Figures are accurate. The titles are specific enough to signal what is included. Check the accuracy of your List of Symbols, Acronyms, and Definitions if you have included any of those.",
  "The Introduction and Conclusion (written after finishing the chapters detailing your research) expand on the Abstract, going into greater detail than is possible in the short Abstract. The first line of the Introduction states the problem and your contribution to solving it. The Introduction gives an overall picture of the contents of the thesis and usually ends with a brief listing of each chapter’s contents. The Conclusion summarizes your findings and discusses their implications; it often ends by suggesting future work. Anyone who reads the Introduction and the Conclusion has an expanded version of the Abstract and a complete summary of the thesis’s contents.",
  "The Related Work / State of Art situates your work within the larger context of your field. This chapter explains how your work grew out of earlier, related research and, in doing so, details the major developments and contrasting approaches in your specific field. You make clear what was the seminal work and then explain both chronologically and thematically the important findings that preceded and motivated your research project. You identify key contributions, issues, and disagreements, and you show the 'links' between the research findings of others. Throughout the chapter, you indicate clearly why we are reading about a specific reference and how it relates to your own research. This tightly argued chapter forms the basis for understanding and validating the importance of your work. It illustrates your skill as a scholar who can identify key papers in your field and then evaluate them. If your thesis relies heavily on your own previously published papers, you may want to incorporate the Literature Review in the body chapters for each of the papers, so that you have a separate Lit Review for each paper. In any case, however, the Literature Review should be in much greater depth in your thesis than is possible in a short paper written for publication.",
  "The ongoing chapters contain sufficient details so that someone else could replicate your work. All chronology is clear.",
  "The body chapters detail your research. The level of detail is sufficient so that your outside reader, who is not intimately familiar with your field, can understand your argument: What did you do? Why did you do it? How did you do it? What was the result? Why should we care about what you did? Why is the work important? Those questions must be answered no matter what field you are in. For example, you cannot just string together a bunch of equations and let your reader figure things out. Don’t merely state; explain! You must lead your reader through your reasoning and your actions to your results. You must clearly identify your contributions, including equipment or procedures you designed, as well as your research results.",
  "Your Bibliography/References (or Works Cited) follows the format acceptable to your field. The Bibliography contains ALL the works cited in your thesis, including visuals, and nothing that is not actually cited. Proofread it for accuracy and consistency. You have to Cite all your references in the text.",
  "You have checked your sentences, paragraphs, sections, and chapters to see if meaning is clear and logically sequential, not to you, but to your outside reader. If you sense that something isn’t clear, believe that it isn’t, and fix it. Ask someone else to read it and note any unclear sentences or sections.",
  "You have checked for logical flow from sentence to sentence, paragraph to paragraph, section to section, chapter to chapter. You have topic sentences that signal a paragraph’s content. Your introductions to each section and chapter signal their contents to the reader.",
  "Table and Figures appear within a page after they are mentioned in the text and not before they are mentioned. Titles are sufficiently detailed; the caption clearly tells the reader what to notice so that it is not necessary to refer to the text in order to understand the illustration. Similarly, the explanation in the text is clear enough to understand without referring to the visual. The visual should complement the text. You have to Cite all your Figures and Tables.",
  "You have proofread for spelling and grammatical errors. If you added words to your dictionary every time you introduced a new one, spellchecking will be far easier. Even so, you will need to proofread to see if you have used the right word. Do not rely on a grammar check program, which misses many errors and sometimes even suggests an incorrect usage.",
  "Headings, sub-headings, lists, and captions are consistent in style and provide useful content. Font size and style, placement of figure and table titles, and margins all meet university requirements and are consistent. If you set up a style sheet when you first started writing, you will have many fewer problems when you are preparing the final draft. If you use the required margins from the time you began writing, too, you won’t now have trouble with graphs, tables, and equations wrapping.",
  "Make certain you have given author citations for all quotations, paraphrases, and borrowed or adapted visuals. Plagiarism is an academic crime."
];
